apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello-world
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: hello-world
  type: LoadBalancer
status:
  loadBalancer: {}
