apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello-world
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: hello-world
  type: LoadBalancer
status:
  loadBalancer: {}
